-- Reseed Task Library & Objective Templates from the
-- SEO Retainer Standard Tasks / OKRs spreadsheet.
-- Depends on: 003_task_library.sql, 012_seed_task_library.sql
--
-- Replaces the previous default library with Distl's canonical objective
-- set (A-K plus SEO Foundations onboarding). Adds a `category` column so
-- templates group in the picker. Existing okr_* rows are snapshots and are
-- not affected.

-- 1. Schema: add category to objective_templates
alter table objective_templates add column if not exists category text;

-- 2. Clear the existing default library (junction cascades from either side)
delete from objective_template_tasks;
delete from objective_templates;
delete from task_library;

-- 3. Tasks
insert into task_library (name, default_am_hours, default_seo_hours, sort_order) values
  ('Keyword Research & Discovery / Validation', 0, 0.5, 0),
  ('Content Optimisation & Expansion (meta, titles, headings, new content)', 0, 4.5, 1),
  ('Client Content Approval & Revisions', 1, 0, 2),
  ('Implement Content (& design if applicable)', 0, 1, 3),
  ('Expand Product / Services Section & internal links', 0, 1, 4),
  ('Publish & Index', 0, 0.5, 5),
  ('Keyword Research & Discovery (new opportunity)', 0, 0.5, 6),
  ('Write New Content & SEO Optimise (titles / metas / URL)', 0, 4.5, 7),
  ('Content Approval & Client Revisions', 1, 0, 8),
  ('Draft / Implement Content & Design on website', 0, 1, 9),
  ('Blog Topic Research & Ideas (title / angle / purpose)', 0, 1, 10),
  ('Blog Strategy & Content Briefs (per blog)', 0.5, 2, 11),
  ('Copywriting / Draft Blog (incl. meta, headings, internal linking)', 0, 2.5, 12),
  ('Blog Review & Feedback / Client Approval', 1, 0, 13),
  ('Optimise, Publish & Index', 0, 1.5, 14),
  ('Audit overlapping pages & plan strategy', 0, 2, 15),
  ('De-optimise / re-optimise competing pages', 0, 3, 16),
  ('Internal linking to clarify the preferred (canonical) page', 0, 1.5, 17),
  ('Consolidate duplicate pages & implement redirects', 0, 3, 18),
  ('Team member bio page creation', 0.5, 3.5, 19),
  ('ProfilePage schema setup & implementation', 0, 4, 20),
  ('Review schema (pull from GBP reviews)', 0, 2, 21),
  ('Technical Audit (priority placeholder, e.g. sitemap changes)', 0, 3.5, 22),
  ('Audit Site for 404s & Redirects - write report', 0, 4, 23),
  ('Resolve issues on key pages', 0, 2, 24),
  ('Set up redirects', 0, 0.5, 25),
  ('Fix internal site health issues (301s, HTTPS, sitemap)', 0, 1, 26),
  ('Schema implementation (FAQ / LocalBusiness / ProfilePage / ItemList / Review)', 0, 3.5, 27),
  ('Correct outdated info across site (pricing, meta data)', 0, 1.5, 28),
  ('GBP optimisation - products / services content', 0, 4, 29),
  ('GBP - write new SEO content (services / products)', 0, 3, 30),
  ('GBP - implement content, image & links', 0, 2.5, 31),
  ('GBP Live Posts', 0, 4, 32),
  ('Citation building / NAP cleanup across directories', 0, 2.5, 33),
  ('Link Prospecting', 0, 2, 34),
  ('Outreach / Draft Request', 0, 1, 35),
  ('Find suitable link & purchase', 0, 0.5, 36),
  ('Link Placement / Publication', 0, 1, 37),
  ('Send link to AM / report', 0.5, 0, 38),
  ('Citations (prepare info + order + provide spreadsheet)', 0, 3, 39),
  ('Receive PR materials / brief from client', 0.5, 0, 40),
  ('Draft PR - long form', 0, 3, 41),
  ('Draft PR - short form', 0, 1, 42),
  ('Draft approval', 1, 0, 43),
  ('Application / purchase process', 0, 2, 44),
  ('Publish & syndicate (GBP post + index in GSC)', 0, 1.5, 45),
  ('Repurpose for blog post', 0, 4, 46),
  ('Audit form UX & identify friction points', 0, 0.5, 47),
  ('Research form platform capabilities / options', 0, 2, 48),
  ('Implement form improvements', 0, 2, 49),
  ('Test & validate functionality', 0, 1, 50),
  ('Onsite conversion tracking setup (incl. live chat / LCM)', 0, 2, 51),
  ('Check GEO retainer eligibility', 0.5, 0.5, 52),
  ('Longtail & heading optimisations for AIO (AI overviews)', 0, 2, 53),
  ('Starter / Inception Meeting', 0.5, 0.5, 54),
  ('Business Information for Citations', 0, 1, 55),
  ('Google Analytics Setup', 0, 1, 56),
  ('Google Tag Manager Setup', 0, 1, 57),
  ('Google Search Console Setup', 0, 0.5, 58),
  ('Agency Analytics Setup', 0, 0.5, 59),
  ('SE Ranking Setup', 0, 0.5, 60),
  ('Keyword Research', 0, 4, 61),
  ('Sitemap Development', 0, 3, 62),
  ('Meta Data Review & Development', 0, 2, 63),
  ('Technical Audit', 0, 4, 64),
  ('Baseline Metrics & Audit Findings Report', 0, 2, 65),
  ('Quarterly OKR Report', 2.5, 5, 66),
  ('Review Results and Plan Upcoming OKRs', 1, 5, 67),
  ('Monthly Reporting', 2.5, 5, 68);

-- 4. Objective templates
insert into objective_templates (title, category, default_scope, sort_order) values
  ('Content Optimisation & Expansion (Existing Page)', 'Content & On-Page', 'specific-pages', 0),
  ('New SEO Landing Page Creation', 'Content & On-Page', 'specific-pages', 1),
  ('Blog Content / Build Topical Authority', 'Content & On-Page', 'sitewide', 2),
  ('Keyword Cannibalisation / Consolidation', 'Content & On-Page', 'specific-pages', 3),
  ('EEAT Optimisation', 'Content & On-Page', 'sitewide', 4),
  ('Technical SEO', 'Technical SEO', 'sitewide', 5),
  ('Local SEO', 'Local SEO', 'sitewide', 6),
  ('Off-site / Link Building', 'Off-site / Authority', 'sitewide', 7),
  ('Digital PR / Brand Awareness', 'Off-site / Authority', 'sitewide', 8),
  ('Conversion Rate Optimisation', 'Conversion & Tracking', 'specific-pages', 9),
  ('GEO / AI Optimisation', 'Emerging / AI', 'sitewide', 10),
  ('SEO Foundations - New Client Onboarding', 'Onboarding', 'sitewide', 11),
  ('Reporting and Planning', 'Reporting & Planning', 'sitewide', 12);

-- 5. Template -> task links
insert into objective_template_tasks (template_id, task_id, sort_order)
select t.id, k.id, x.ord
from (values
  ('Content Optimisation & Expansion (Existing Page)', 'Keyword Research & Discovery / Validation', 0),
  ('Content Optimisation & Expansion (Existing Page)', 'Content Optimisation & Expansion (meta, titles, headings, new content)', 1),
  ('Content Optimisation & Expansion (Existing Page)', 'Client Content Approval & Revisions', 2),
  ('Content Optimisation & Expansion (Existing Page)', 'Implement Content (& design if applicable)', 3),
  ('Content Optimisation & Expansion (Existing Page)', 'Expand Product / Services Section & internal links', 4),
  ('Content Optimisation & Expansion (Existing Page)', 'Publish & Index', 5),
  ('New SEO Landing Page Creation', 'Keyword Research & Discovery (new opportunity)', 0),
  ('New SEO Landing Page Creation', 'Write New Content & SEO Optimise (titles / metas / URL)', 1),
  ('New SEO Landing Page Creation', 'Content Approval & Client Revisions', 2),
  ('New SEO Landing Page Creation', 'Draft / Implement Content & Design on website', 3),
  ('New SEO Landing Page Creation', 'Publish & Index', 4),
  ('Blog Content / Build Topical Authority', 'Blog Topic Research & Ideas (title / angle / purpose)', 0),
  ('Blog Content / Build Topical Authority', 'Blog Strategy & Content Briefs (per blog)', 1),
  ('Blog Content / Build Topical Authority', 'Copywriting / Draft Blog (incl. meta, headings, internal linking)', 2),
  ('Blog Content / Build Topical Authority', 'Blog Review & Feedback / Client Approval', 3),
  ('Blog Content / Build Topical Authority', 'Optimise, Publish & Index', 4),
  ('Keyword Cannibalisation / Consolidation', 'Audit overlapping pages & plan strategy', 0),
  ('Keyword Cannibalisation / Consolidation', 'De-optimise / re-optimise competing pages', 1),
  ('Keyword Cannibalisation / Consolidation', 'Internal linking to clarify the preferred (canonical) page', 2),
  ('Keyword Cannibalisation / Consolidation', 'Consolidate duplicate pages & implement redirects', 3),
  ('EEAT Optimisation', 'Team member bio page creation', 0),
  ('EEAT Optimisation', 'ProfilePage schema setup & implementation', 1),
  ('EEAT Optimisation', 'Review schema (pull from GBP reviews)', 2),
  ('Technical SEO', 'Technical Audit (priority placeholder, e.g. sitemap changes)', 0),
  ('Technical SEO', 'Audit Site for 404s & Redirects - write report', 1),
  ('Technical SEO', 'Resolve issues on key pages', 2),
  ('Technical SEO', 'Set up redirects', 3),
  ('Technical SEO', 'Fix internal site health issues (301s, HTTPS, sitemap)', 4),
  ('Technical SEO', 'Schema implementation (FAQ / LocalBusiness / ProfilePage / ItemList / Review)', 5),
  ('Technical SEO', 'Correct outdated info across site (pricing, meta data)', 6),
  ('Local SEO', 'GBP optimisation - products / services content', 0),
  ('Local SEO', 'GBP - write new SEO content (services / products)', 1),
  ('Local SEO', 'GBP - implement content, image & links', 2),
  ('Local SEO', 'GBP Live Posts', 3),
  ('Local SEO', 'Citation building / NAP cleanup across directories', 4),
  ('Off-site / Link Building', 'Link Prospecting', 0),
  ('Off-site / Link Building', 'Outreach / Draft Request', 1),
  ('Off-site / Link Building', 'Find suitable link & purchase', 2),
  ('Off-site / Link Building', 'Link Placement / Publication', 3),
  ('Off-site / Link Building', 'Send link to AM / report', 4),
  ('Off-site / Link Building', 'Citations (prepare info + order + provide spreadsheet)', 5),
  ('Digital PR / Brand Awareness', 'Receive PR materials / brief from client', 0),
  ('Digital PR / Brand Awareness', 'Draft PR - long form', 1),
  ('Digital PR / Brand Awareness', 'Draft PR - short form', 2),
  ('Digital PR / Brand Awareness', 'Draft approval', 3),
  ('Digital PR / Brand Awareness', 'Application / purchase process', 4),
  ('Digital PR / Brand Awareness', 'Publish & syndicate (GBP post + index in GSC)', 5),
  ('Digital PR / Brand Awareness', 'Repurpose for blog post', 6),
  ('Conversion Rate Optimisation', 'Audit form UX & identify friction points', 0),
  ('Conversion Rate Optimisation', 'Research form platform capabilities / options', 1),
  ('Conversion Rate Optimisation', 'Implement form improvements', 2),
  ('Conversion Rate Optimisation', 'Test & validate functionality', 3),
  ('Conversion Rate Optimisation', 'Onsite conversion tracking setup (incl. live chat / LCM)', 4),
  ('GEO / AI Optimisation', 'Check GEO retainer eligibility', 0),
  ('GEO / AI Optimisation', 'Longtail & heading optimisations for AIO (AI overviews)', 1),
  ('SEO Foundations - New Client Onboarding', 'Starter / Inception Meeting', 0),
  ('SEO Foundations - New Client Onboarding', 'Business Information for Citations', 1),
  ('SEO Foundations - New Client Onboarding', 'Google Analytics Setup', 2),
  ('SEO Foundations - New Client Onboarding', 'Google Tag Manager Setup', 3),
  ('SEO Foundations - New Client Onboarding', 'Google Search Console Setup', 4),
  ('SEO Foundations - New Client Onboarding', 'Agency Analytics Setup', 5),
  ('SEO Foundations - New Client Onboarding', 'SE Ranking Setup', 6),
  ('SEO Foundations - New Client Onboarding', 'Keyword Research', 7),
  ('SEO Foundations - New Client Onboarding', 'Sitemap Development', 8),
  ('SEO Foundations - New Client Onboarding', 'Meta Data Review & Development', 9),
  ('SEO Foundations - New Client Onboarding', 'Technical Audit', 10),
  ('SEO Foundations - New Client Onboarding', 'Baseline Metrics & Audit Findings Report', 11),
  ('Reporting and Planning', 'Quarterly OKR Report', 0),
  ('Reporting and Planning', 'Review Results and Plan Upcoming OKRs', 1),
  ('Reporting and Planning', 'Monthly Reporting', 2)
) as x(tpl_title, task_name, ord)
join objective_templates t on t.title = x.tpl_title
join task_library k on k.name = x.task_name;
